# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/progs/ccom

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/progs/ccom

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/progs/ccom/CMakeFiles /home/pi/progs/ccom/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/progs/ccom/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named prog

# Build rule for target.
prog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prog
.PHONY : prog

# fast build rule for target.
prog/fast:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/build
.PHONY : prog/fast

src/CHS.o: src/CHS.c.o
.PHONY : src/CHS.o

# target to build an object file
src/CHS.c.o:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/CHS.c.o
.PHONY : src/CHS.c.o

src/CHS.i: src/CHS.c.i
.PHONY : src/CHS.i

# target to preprocess a source file
src/CHS.c.i:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/CHS.c.i
.PHONY : src/CHS.c.i

src/CHS.s: src/CHS.c.s
.PHONY : src/CHS.s

# target to generate assembly for a file
src/CHS.c.s:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/CHS.c.s
.PHONY : src/CHS.c.s

src/Terabus.o: src/Terabus.c.o
.PHONY : src/Terabus.o

# target to build an object file
src/Terabus.c.o:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/Terabus.c.o
.PHONY : src/Terabus.c.o

src/Terabus.i: src/Terabus.c.i
.PHONY : src/Terabus.i

# target to preprocess a source file
src/Terabus.c.i:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/Terabus.c.i
.PHONY : src/Terabus.c.i

src/Terabus.s: src/Terabus.c.s
.PHONY : src/Terabus.s

# target to generate assembly for a file
src/Terabus.c.s:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/Terabus.c.s
.PHONY : src/Terabus.c.s

src/UartDriver.o: src/UartDriver.c.o
.PHONY : src/UartDriver.o

# target to build an object file
src/UartDriver.c.o:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/UartDriver.c.o
.PHONY : src/UartDriver.c.o

src/UartDriver.i: src/UartDriver.c.i
.PHONY : src/UartDriver.i

# target to preprocess a source file
src/UartDriver.c.i:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/UartDriver.c.i
.PHONY : src/UartDriver.c.i

src/UartDriver.s: src/UartDriver.c.s
.PHONY : src/UartDriver.s

# target to generate assembly for a file
src/UartDriver.c.s:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/UartDriver.c.s
.PHONY : src/UartDriver.c.s

src/UartManager.o: src/UartManager.c.o
.PHONY : src/UartManager.o

# target to build an object file
src/UartManager.c.o:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/UartManager.c.o
.PHONY : src/UartManager.c.o

src/UartManager.i: src/UartManager.c.i
.PHONY : src/UartManager.i

# target to preprocess a source file
src/UartManager.c.i:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/UartManager.c.i
.PHONY : src/UartManager.c.i

src/UartManager.s: src/UartManager.c.s
.PHONY : src/UartManager.s

# target to generate assembly for a file
src/UartManager.c.s:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/UartManager.c.s
.PHONY : src/UartManager.c.s

src/connect.o: src/connect.c.o
.PHONY : src/connect.o

# target to build an object file
src/connect.c.o:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/connect.c.o
.PHONY : src/connect.c.o

src/connect.i: src/connect.c.i
.PHONY : src/connect.i

# target to preprocess a source file
src/connect.c.i:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/connect.c.i
.PHONY : src/connect.c.i

src/connect.s: src/connect.c.s
.PHONY : src/connect.s

# target to generate assembly for a file
src/connect.c.s:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/connect.c.s
.PHONY : src/connect.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... prog"
	@echo "... rebuild_cache"
	@echo "... src/CHS.o"
	@echo "... src/CHS.i"
	@echo "... src/CHS.s"
	@echo "... src/Terabus.o"
	@echo "... src/Terabus.i"
	@echo "... src/Terabus.s"
	@echo "... src/UartDriver.o"
	@echo "... src/UartDriver.i"
	@echo "... src/UartDriver.s"
	@echo "... src/UartManager.o"
	@echo "... src/UartManager.i"
	@echo "... src/UartManager.s"
	@echo "... src/connect.o"
	@echo "... src/connect.i"
	@echo "... src/connect.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

